CREATE TABLE IF NOT EXISTS students
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    email  VARCHAR(100)
    );
CREATE TABLE IF NOT EXISTS faculty
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
    );
CREATE TABLE IF NOT EXISTS task
(
    id		 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(100),
    student_id BIGINT,
    FOREIGN KEY(student_id) REFERENCES students(id)
    );
CREATE TABLE IF NOT EXISTS student_faculty (
                                               student_id 	BIGINT NOT NULL,
                                               faculty_id 	BIGINT NOT NULL,
                                               PRIMARY KEY (student_id, faculty_id),
    FOREIGN KEY(student_id) REFERENCES student(id),
    FOREIGN KEY(faculty_id) REFERENCES cofaculty(id)
    );